In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.Series([0.25,0.5,0.75,1.0],
                 index=["a", "b", "c", "d"])

In [3]:
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [4]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In [5]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [8]:
indA & indB ### intersection, sadece ortakları alır

Index([0, 3, 5, 7, 9], dtype='int64')

In [9]:
indA | indB ### union

Index([3, 3, 5, 7, 11], dtype='int64')

In [10]:
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5])

In [11]:
data[1]

'a'

In [18]:
data[::2]

1    a
5    c
dtype: object

In [20]:
area = pd.Series({'California': 423967, 'Texas': 695662,
 'New York': 141297, 'Florida': 170312,
 'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
 'New York': 19651127, 'Florida': 19552860,
 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})

In [21]:
data

              area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [22]:
data.T

      California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

In [23]:
data.values[0]

array([  423967, 38332521])

In [24]:
data = pd.Series([1, np.nan, 'hello', None])

In [26]:
data[data.isnull()]

1     NaN
3    None
dtype: object

In [27]:
data = pd.Series([1, np.nan, 2, None, 3], index=list('abcde'))

In [28]:
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [29]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [ ]:
data.fillna(method= "ffill") ## bir sonraki değerle doldurur.

/var/folders/sj/pj9lwv9d1r17b6cggf8ym3gc0000gn/T/ipykernel_1371/759131408.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method= "ffill")

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [ ]:
data.fillna(method= "bfill") ## bir önceki değerle doldurur.

/var/folders/sj/pj9lwv9d1r17b6cggf8ym3gc0000gn/T/ipykernel_1371/2774565433.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method= "bfill")

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [33]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
 'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
 'hire_date': [2004, 2008, 2012, 2014]})

In [36]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [37]:
df2

  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

In [48]:
df3 = pd.merge(df1, df2) ## 2 farklı dataframein birleştirilmesi

In [49]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [50]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
 'supervisor': ['Carly', 'Guido', 'Steve']})

In [51]:
df4

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve

In [52]:
df3

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [75]:
df3[df3["employee"] == 'Bob']["group"].replace("Accounting", "Analyst", inplace= True)

/var/folders/sj/pj9lwv9d1r17b6cggf8ym3gc0000gn/T/ipykernel_1371/3337411769.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3[df3["employee"] == 'Bob']["group"].replace("Accounting", "Analyst", inplace= True)

In [79]:
df3.loc[
    (df3["employee"] == 'Bob') & (df3["group"] == 'Accounting'),
    "group"
] = 'Analyst'

In [80]:
df3

  employee        group  hire_date
0      Bob      Analyst       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [42]:
df5 = pd.merge(df3, df4) ## 2 farklı dataframein birleştirilmesi

In [43]:
df5

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve