In [2]:
import pandas as pd
import numpy as np

### Pandas

In [4]:
## Pandas'ın Kullanım Amacı

Pandas'ın ML pipelinedaki yeri aşağıdaki şekilde: <p>
-- Veriyi oku (CSV, Excel vs.)

-- Temizle (missing, hatalı veri)

-- Dönüştür (feature engineering)

-- Analiz et (EDA)

-- Modele hazır hale getir

In [5]:
data = np.random.randn(4,3)

In [6]:
data

array([[-0.0696306 ,  0.48755519,  0.65003228],
       [-0.7896255 ,  0.24079355, -0.16626509],
       [ 1.1653175 , -2.52371937,  0.16841667],
       [ 0.16424383, -0.76186258,  2.31131531]])

In [10]:
## Dataframe oluşturulması ve column, index adlarının atanması

In [8]:
data_frame = pd.DataFrame(data, index = ['Tito', 'Tuğçe', 'Fatih', 'Toto'], columns = ["Age", "Seniority", "Experience"])

In [9]:
data_frame

            Age  Seniority  Experience
Tito  -0.069631   0.487555    0.650032
Tuğçe -0.789626   0.240794   -0.166265
Fatih  1.165317  -2.523719    0.168417
Toto   0.164244  -0.761863    2.311315

In [11]:
## Tek bir kolon almak

In [13]:
data_frame["Age"]

Tito    -0.069631
Tuğçe   -0.789626
Fatih    1.165317
Toto     0.164244
Name: Age, dtype: float64

In [14]:
## Birden fazla kolon almak

In [16]:
data_frame[["Age", "Seniority"]]

            Age  Seniority
Tito  -0.069631   0.487555
Tuğçe -0.789626   0.240794
Fatih  1.165317  -2.523719
Toto   0.164244  -0.761863

In [18]:
## Satır almak (index(iloc) ve kolon adı(loc) olarak

In [20]:
data_frame.loc["Tito"]

Age          -0.069631
Seniority     0.487555
Experience    0.650032
Name: Tito, dtype: float64

In [21]:
data_frame.iloc[1]

Age          -0.789626
Seniority     0.240794
Experience   -0.166265
Name: Tuğçe, dtype: float64

In [39]:
## Yeni kolon eklemek ve kolonu silmek

In [41]:
data_frame["Adress"] = 10

In [42]:
data_frame

            Age  Seniority  Experience  Adress
Tito  -0.069631   0.487555    0.650032      10
Tuğçe -0.789626   0.240794   -0.166265      10
Fatih  1.165317  -2.523719    0.168417      10
Toto   0.164244  -0.761863    2.311315      10

In [43]:
data_frame = data_frame.drop("Adress", axis = 1) ## droplama yol 1

In [44]:
data_frame

            Age  Seniority  Experience
Tito  -0.069631   0.487555    0.650032
Tuğçe -0.789626   0.240794   -0.166265
Fatih  1.165317  -2.523719    0.168417
Toto   0.164244  -0.761863    2.311315

In [45]:
data_frame["Hours"] = 10

In [46]:
data_frame

            Age  Seniority  Experience  Hours
Tito  -0.069631   0.487555    0.650032     10
Tuğçe -0.789626   0.240794   -0.166265     10
Fatih  1.165317  -2.523719    0.168417     10
Toto   0.164244  -0.761863    2.311315     10

In [47]:
data_frame.drop("Hours", axis = 1, inplace = True) ## inplace = true ile yapılan değişiklik ana df'e kaydedildi.

In [51]:
data_frame

            Age  Seniority  Experience
Tito  -0.069631   0.487555    0.650032
Tuğçe -0.789626   0.240794   -0.166265
Fatih  1.165317  -2.523719    0.168417
Toto   0.164244  -0.761863    2.311315

##### belirli bir kolonun belirli bir satırını almak için: <p>
-- 2 yol var: <p>
    1) .loc sonrasında kolon ve sütunun adlarını ayrı ayrı parantezlere almak <p>
    2) .loc sonrasında hem kolon hem sütun adının aynı parantez içerisinde yer alması

In [53]:
data_frame.loc["Tito"]["Age"]

np.float64(-0.06963060089820461)

In [55]:
data_frame.loc["Tito","Age"]

np.float64(-0.06963060089820461)

In [60]:
## filtrelemeler

In [61]:
data_frame > 0

         Age  Seniority  Experience
Tito   False       True        True
Tuğçe  False       True       False
Fatih   True      False        True
Toto    True      False        True

In [59]:
data_frame[data_frame["Seniority"] > 0]

            Age  Seniority  Experience
Tito  -0.069631   0.487555    0.650032
Tuğçe -0.789626   0.240794   -0.166265

### İndex Mantığı

In [62]:
data_frame.reset_index()

   index       Age  Seniority  Experience
0   Tito -0.069631   0.487555    0.650032
1  Tuğçe -0.789626   0.240794   -0.166265
2  Fatih  1.165317  -2.523719    0.168417
3   Toto  0.164244  -0.761863    2.311315

In [63]:
data_frame

            Age  Seniority  Experience
Tito  -0.069631   0.487555    0.650032
Tuğçe -0.789626   0.240794   -0.166265
Fatih  1.165317  -2.523719    0.168417
Toto   0.164244  -0.761863    2.311315

In [64]:
reset_frame = data_frame.reset_index()

In [65]:
reset_frame.loc[0]

index             Tito
Age          -0.069631
Seniority     0.487555
Experience    0.650032
Name: 0, dtype: object

In [70]:
### Yeni index belirleme

In [66]:
new_indices = ["Ti", "Tuğ", "Ay", "To"]

In [68]:
data_frame["NewIndex"] = new_indices

In [69]:
data_frame

            Age  Seniority  Experience NewIndex
Tito  -0.069631   0.487555    0.650032       Ti
Tuğçe -0.789626   0.240794   -0.166265      Tuğ
Fatih  1.165317  -2.523719    0.168417       Ay
Toto   0.164244  -0.761863    2.311315       To

In [71]:
### Yeni index atama

In [72]:
data_frame.set_index("NewIndex", inplace = True)

In [73]:
data_frame

               Age  Seniority  Experience
NewIndex
Ti       -0.069631   0.487555    0.650032
Tuğ      -0.789626   0.240794   -0.166265
Ay        1.165317  -2.523719    0.168417
To        0.164244  -0.761863    2.311315

In [75]:
data_frame.loc["Ti"]

Age          -0.069631
Seniority     0.487555
Experience    0.650032
Name: Ti, dtype: float64

In [82]:
weather_df = pd.read_excel('6-weather.xlsx')

In [83]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [94]:
## data keşfi

In [84]:
## ilk 5 ve son 5 satır

In [85]:
weather_df.head()

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [86]:
weather_df.tail()

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [87]:
## df ile ilgili genel bilgi

In [89]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [90]:
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [91]:
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [92]:
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

In [95]:
### eksik datalarla çalışmak

In [96]:
weather_na_df = pd.read_excel("6-weatherna.xlsx")

In [97]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [98]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [99]:
weather_na_df["Paris"].isna()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
Name: Paris, dtype: bool

In [100]:
weather_na_df["Paris"].count()

np.int64(6)

In [104]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [102]:
## eksik datalara karşı aksiyon almak

In [105]:
weather_na_df.dropna() ## rowda en az 1 tane row varsa direkt siliyor. ideal değil.

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [106]:
## direkt olarak 1 kolonu drop etmek

In [107]:
weather_na_df.drop('Paris', axis = 1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [109]:
weather_na_df.fillna(0) ## bütün na'leri tek bir değer ile değiştirdik.

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        0.0   14.0
2       0.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       0.0       22.0    0.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    0.0
8      22.0      16.0       16.0    0.0

In [110]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [112]:
weather_na_df.fillna(weather_na_df.mean()) ## boşlukları ilgili ülkenin meani ile doldurduk.

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667