In [137]:
import pandas as pd
import numpy as np

### Pandas

In [138]:
## Pandas'ın Kullanım Amacı

Pandas'ın ML pipelinedaki yeri aşağıdaki şekilde: <p>
-- Veriyi oku (CSV, Excel vs.)

-- Temizle (missing, hatalı veri)

-- Dönüştür (feature engineering)

-- Analiz et (EDA)

-- Modele hazır hale getir

In [139]:
data = np.random.randn(4,3)

In [140]:
data

array([[ 0.0560611 , -0.27658748,  0.69502876],
       [ 0.45477901, -0.4102553 ,  0.50712936],
       [-0.71580494, -1.23805792, -1.51319406],
       [ 0.0491564 ,  1.23668547,  0.5191091 ]])

In [141]:
## Dataframe oluşturulması ve column, index adlarının atanması

In [142]:
data_frame = pd.DataFrame(data, index = ['Tito', 'Tuğçe', 'Fatih', 'Toto'], columns = ["Age", "Seniority", "Experience"])

In [143]:
data_frame

            Age  Seniority  Experience
Tito   0.056061  -0.276587    0.695029
Tuğçe  0.454779  -0.410255    0.507129
Fatih -0.715805  -1.238058   -1.513194
Toto   0.049156   1.236685    0.519109

In [144]:
## Tek bir kolon almak

In [145]:
data_frame["Age"]

Tito     0.056061
Tuğçe    0.454779
Fatih   -0.715805
Toto     0.049156
Name: Age, dtype: float64

In [146]:
## Birden fazla kolon almak

In [147]:
data_frame[["Age", "Seniority"]]

            Age  Seniority
Tito   0.056061  -0.276587
Tuğçe  0.454779  -0.410255
Fatih -0.715805  -1.238058
Toto   0.049156   1.236685

In [148]:
## Satır almak (index(iloc) ve kolon adı(loc) olarak

In [149]:
data_frame.loc["Tito"]

Age           0.056061
Seniority    -0.276587
Experience    0.695029
Name: Tito, dtype: float64

In [150]:
data_frame.iloc[1]

Age           0.454779
Seniority    -0.410255
Experience    0.507129
Name: Tuğçe, dtype: float64

In [151]:
## Yeni kolon eklemek ve kolonu silmek

In [152]:
data_frame["Adress"] = 10

In [153]:
data_frame

            Age  Seniority  Experience  Adress
Tito   0.056061  -0.276587    0.695029      10
Tuğçe  0.454779  -0.410255    0.507129      10
Fatih -0.715805  -1.238058   -1.513194      10
Toto   0.049156   1.236685    0.519109      10

In [154]:
data_frame = data_frame.drop("Adress", axis = 1) ## droplama yol 1

In [155]:
data_frame

            Age  Seniority  Experience
Tito   0.056061  -0.276587    0.695029
Tuğçe  0.454779  -0.410255    0.507129
Fatih -0.715805  -1.238058   -1.513194
Toto   0.049156   1.236685    0.519109

In [156]:
data_frame["Hours"] = 10

In [157]:
data_frame

            Age  Seniority  Experience  Hours
Tito   0.056061  -0.276587    0.695029     10
Tuğçe  0.454779  -0.410255    0.507129     10
Fatih -0.715805  -1.238058   -1.513194     10
Toto   0.049156   1.236685    0.519109     10

In [158]:
data_frame.drop("Hours", axis = 1, inplace = True) ## inplace = true ile yapılan değişiklik ana df'e kaydedildi.

In [159]:
data_frame

            Age  Seniority  Experience
Tito   0.056061  -0.276587    0.695029
Tuğçe  0.454779  -0.410255    0.507129
Fatih -0.715805  -1.238058   -1.513194
Toto   0.049156   1.236685    0.519109

##### belirli bir kolonun belirli bir satırını almak için: <p>
-- 2 yol var: <p>
    1) .loc sonrasında kolon ve sütunun adlarını ayrı ayrı parantezlere almak <p>
    2) .loc sonrasında hem kolon hem sütun adının aynı parantez içerisinde yer alması

In [160]:
data_frame.loc["Tito"]["Age"]

np.float64(0.05606110151694264)

In [161]:
data_frame.loc["Tito","Age"]

np.float64(0.05606110151694264)

In [162]:
## filtrelemeler

In [163]:
data_frame > 0

         Age  Seniority  Experience
Tito    True      False        True
Tuğçe   True      False        True
Fatih  False      False       False
Toto    True       True        True

In [164]:
data_frame[data_frame["Seniority"] > 0]

           Age  Seniority  Experience
Toto  0.049156   1.236685    0.519109

### İndex Mantığı

In [165]:
data_frame.reset_index()

   index       Age  Seniority  Experience
0   Tito  0.056061  -0.276587    0.695029
1  Tuğçe  0.454779  -0.410255    0.507129
2  Fatih -0.715805  -1.238058   -1.513194
3   Toto  0.049156   1.236685    0.519109

In [166]:
data_frame

            Age  Seniority  Experience
Tito   0.056061  -0.276587    0.695029
Tuğçe  0.454779  -0.410255    0.507129
Fatih -0.715805  -1.238058   -1.513194
Toto   0.049156   1.236685    0.519109

In [167]:
reset_frame = data_frame.reset_index()

In [168]:
reset_frame.loc[0]

index             Tito
Age           0.056061
Seniority    -0.276587
Experience    0.695029
Name: 0, dtype: object

In [169]:
### Yeni index belirleme

In [170]:
new_indices = ["Ti", "Tuğ", "Ay", "To"]

In [171]:
data_frame["NewIndex"] = new_indices

In [172]:
data_frame

            Age  Seniority  Experience NewIndex
Tito   0.056061  -0.276587    0.695029       Ti
Tuğçe  0.454779  -0.410255    0.507129      Tuğ
Fatih -0.715805  -1.238058   -1.513194       Ay
Toto   0.049156   1.236685    0.519109       To

In [173]:
### Yeni index atama

In [174]:
data_frame.set_index("NewIndex", inplace = True)

In [175]:
data_frame

               Age  Seniority  Experience
NewIndex
Ti        0.056061  -0.276587    0.695029
Tuğ       0.454779  -0.410255    0.507129
Ay       -0.715805  -1.238058   -1.513194
To        0.049156   1.236685    0.519109

In [176]:
data_frame.loc["Ti"]

Age           0.056061
Seniority    -0.276587
Experience    0.695029
Name: Ti, dtype: float64

In [177]:
weather_df = pd.read_excel('6-weather.xlsx')

In [178]:
weather_df

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [179]:
## data keşfi

In [180]:
## ilk 5 ve son 5 satır

In [181]:
weather_df.head()

   Istanbul  New York  Amsterdam  Paris
0        20        10         15     12
1        21        10         17     14
2        20        13         18     15
3        22        14         19     18
4        25        15         15     20

In [182]:
weather_df.tail()

   Istanbul  New York  Amsterdam  Paris
4        25        15         15     20
5        28        13         22     16
6        15        12         15     15
7        20        15         14     14
8        22        16         16     16

In [183]:
## df ile ilgili genel bilgi

In [184]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Istanbul   9 non-null      int64
 1   New York   9 non-null      int64
 2   Amsterdam  9 non-null      int64
 3   Paris      9 non-null      int64
dtypes: int64(4)
memory usage: 420.0 bytes

In [185]:
weather_df.describe()

        Istanbul   New York  Amsterdam      Paris
count   9.000000   9.000000   9.000000   9.000000
mean   21.444444  13.111111  16.777778  15.555556
std     3.609401   2.147350   2.538591   2.351123
min    15.000000  10.000000  14.000000  12.000000
25%    20.000000  12.000000  15.000000  14.000000
50%    21.000000  13.000000  16.000000  15.000000
75%    22.000000  15.000000  18.000000  16.000000
max    28.000000  16.000000  22.000000  20.000000

In [186]:
weather_df.count()

Istanbul     9
New York     9
Amsterdam    9
Paris        9
dtype: int64

In [187]:
weather_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False      False  False
2     False     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False     False      False  False
6     False     False      False  False
7     False     False      False  False
8     False     False      False  False

In [188]:
### eksik datalarla çalışmak

In [189]:
weather_na_df = pd.read_excel("6-weatherna.xlsx")

In [190]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [191]:
weather_na_df.isna()

   Istanbul  New York  Amsterdam  Paris
0     False     False      False  False
1     False     False       True  False
2      True     False      False  False
3     False     False      False  False
4     False     False      False  False
5     False      True      False   True
6     False     False      False  False
7     False     False      False   True
8     False     False      False   True

In [192]:
weather_na_df["Paris"].isna()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7     True
8     True
Name: Paris, dtype: bool

In [193]:
weather_na_df["Paris"].count()

np.int64(6)

In [194]:
weather_na_df

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        NaN   14.0
2       NaN      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       NaN       22.0    NaN
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    NaN
8      22.0      16.0       16.0    NaN

In [195]:
## eksik datalara karşı aksiyon almak

In [196]:
weather_na_df.dropna() ## rowda en az 1 tane row varsa direkt siliyor. ideal değil.

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
6      15.0      12.0       15.0   15.0

In [197]:
## direkt olarak 1 kolonu drop etmek

In [198]:
weather_na_df.drop('Paris', axis = 1)

   Istanbul  New York  Amsterdam
0      20.0      10.0       15.0
1      21.0      10.0        NaN
2       NaN      13.0       18.0
3      22.0      14.0       19.0
4      25.0      15.0       15.0
5      28.0       NaN       22.0
6      15.0      12.0       15.0
7      20.0      15.0       14.0
8      22.0      16.0       16.0

In [199]:
weather_na_df.fillna(0) ## bütün na'leri tek bir değer ile değiştirdik.

   Istanbul  New York  Amsterdam  Paris
0      20.0      10.0       15.0   12.0
1      21.0      10.0        0.0   14.0
2       0.0      13.0       18.0   15.0
3      22.0      14.0       19.0   18.0
4      25.0      15.0       15.0   20.0
5      28.0       0.0       22.0    0.0
6      15.0      12.0       15.0   15.0
7      20.0      15.0       14.0    0.0
8      22.0      16.0       16.0    0.0

In [200]:
weather_na_df.mean()

Istanbul     21.625000
New York     13.125000
Amsterdam    16.750000
Paris        15.666667
dtype: float64

In [201]:
weather_na_df.fillna(weather_na_df.mean()) ## boşlukları ilgili ülkenin meani ile doldurduk.

   Istanbul  New York  Amsterdam      Paris
0    20.000    10.000      15.00  12.000000
1    21.000    10.000      16.75  14.000000
2    21.625    13.000      18.00  15.000000
3    22.000    14.000      19.00  18.000000
4    25.000    15.000      15.00  20.000000
5    28.000    13.125      22.00  15.666667
6    15.000    12.000      15.00  15.000000
7    20.000    15.000      14.00  15.666667
8    22.000    16.000      16.00  15.666667

### Pandas Groupby

In [202]:
df = pd.read_csv('6-employee.csv')

In [203]:
df

   Department Employee  Salary  Experience           City
0   Marketing    Emp_1   53483           1       New York
1       Sales    Emp_2   78555           8         Austin
2     Finance    Emp_3   47159           3         Austin
3       Sales    Emp_4  110077           3  San Francisco
4       Sales    Emp_5   65920           1       New York
5          IT    Emp_6   97121          11        Chicago
6     Finance    Emp_7   99479           5        Chicago
7     Finance    Emp_8  119475          10       New York
8     Finance    Emp_9   49457           7        Chicago
9       Sales   Emp_10   96557          10        Chicago
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
12      Sales   Emp_13   82995           7       New York
13         IT   Emp_14   70757           9         Austin
14  Marketing   Emp_15   39692           8        Chicago
15         IT   Emp_16   75758          12        Chicago
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
18         HR   Emp_19   95697           7         Austin
19  Marketing   Emp_20   67065           7  San Francisco
20         IT   Emp_21   62606          14  San Francisco
21      Sales   Emp_22   41534           8       New York
22  Marketing   Emp_23   70397           5  San Francisco
23         HR   Emp_24   31016           3       New York
24         HR   Emp_25  119789          12       New York
25    Finance   Emp_26   85591           8  San Francisco
26    Finance   Emp_27  119812           6         Austin
27         IT   Emp_28   53247          11         Austin
28  Marketing   Emp_29   54300           3         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
31  Marketing   Emp_32   39268           5  San Francisco
32  Marketing   Emp_33  116807          14  San Francisco
33         HR   Emp_34   42185           3        Chicago
34    Finance   Emp_35   93704           1         Austin
35      Sales   Emp_36  116779           5  San Francisco
36    Finance   Emp_37   69099          10        Chicago
37      Sales   Emp_38   38571           7         Austin
38         HR   Emp_39   68044          14       New York
39         IT   Emp_40   81214           7        Chicago
40  Marketing   Emp_41   91228          11  San Francisco
41         HR   Emp_42   78984           9       New York
42  Marketing   Emp_43   70774          10       New York
43         IT   Emp_44   32568          10       New York
44         IT   Emp_45   92592          12        Chicago
45         HR   Emp_46   97563          13  San Francisco
46         IT   Emp_47   32695           3       New York
47      Sales   Emp_48   78190           7         Austin
48         IT   Emp_49   35258           1       New York
49  Marketing   Emp_50  117538           4       New York

In [204]:
### data tanımlamaları

In [205]:
df.describe()

              Salary  Experience
count      50.000000   50.000000
mean    78344.500000    7.060000
std     27817.603904    3.966235
min     31016.000000    1.000000
25%     53687.250000    3.000000
50%     78769.500000    7.000000
75%    100778.000000   10.000000
max    119812.000000   14.000000

In [206]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Department  50 non-null     object
 1   Employee    50 non-null     object
 2   Salary      50 non-null     int64
 3   Experience  50 non-null     int64
 4   City        50 non-null     object
dtypes: int64(2), object(3)
memory usage: 2.1+ KB

In [207]:
df["Salary"].mean()

np.float64(78344.5)

In [208]:
df[["Salary", "Experience"]].mean()

Salary        78344.50
Experience        7.06
dtype: float64

In [209]:
df[df["Salary"] > 100000]

   Department Employee  Salary  Experience           City
3       Sales    Emp_4  110077           3  San Francisco
7     Finance    Emp_8  119475          10       New York
10  Marketing   Emp_11  107189           9       New York
11    Finance   Emp_12  108953          12         Austin
16  Marketing   Emp_17  102409           2        Chicago
17      Sales   Emp_18  101211           1  San Francisco
24         HR   Emp_25  119789          12       New York
26    Finance   Emp_27  119812           6         Austin
29  Marketing   Emp_30  104065           1         Austin
30    Finance   Emp_31  112798           3         Austin
32  Marketing   Emp_33  116807          14  San Francisco
35      Sales   Emp_36  116779           5  San Francisco
49  Marketing   Emp_50  117538           4       New York

In [210]:
df[df["Salary"] > 100000].count()

Department    13
Employee      13
Salary        13
Experience    13
City          13
dtype: int64

In [211]:
df_grouped = df.groupby("Department")

In [212]:
df_grouped.count()

            Employee  Salary  Experience  City
Department
Finance           10      10          10    10
HR                 7       7           7     7
IT                10      10          10    10
Marketing         13      13          13    13
Sales             10      10          10    10

In [213]:
df_grouped.describe()

           Salary                                                          \
            count          mean           std      min       25%      50%
Department
Finance      10.0  90552.700000  27228.231832  47159.0  73222.00  96591.5
HR            7.0  76182.571429  31647.523983  31016.0  55114.50  78984.0
IT           10.0  63381.600000  24272.881041  32568.0  39755.25  66681.5
Marketing    13.0  79555.000000  28431.207129  39268.0  54300.00  70774.0
Sales        10.0  81038.900000  26623.181534  38571.0  68987.50  80775.0

                                Experience                                \
                  75%       max      count      mean       std  min  25%
Department
Finance     111836.75  119812.0       10.0  6.500000  3.566822  1.0  3.5
HR           96630.00  119789.0        7.0  8.714286  4.572173  3.0  5.0
IT           79850.00   97121.0       10.0  9.000000  4.163332  1.0  7.5
Marketing   104065.00  117538.0       13.0  6.153846  4.079341  1.0  3.0
Sales       100047.50  116779.0       10.0  5.700000  3.093003  1.0  3.5


             50%    75%   max
Department
Finance      6.5   9.50  12.0
HR           9.0  12.50  14.0
IT          10.5  11.75  14.0
Marketing    5.0   9.00  14.0
Sales        7.0   7.75  10.0

In [214]:
df_grouped["Salary"].mean()

Department
Finance      90552.700000
HR           76182.571429
IT           63381.600000
Marketing    79555.000000
Sales        81038.900000
Name: Salary, dtype: float64

In [215]:
df_city = df.groupby("City")

In [216]:
df_city["Salary"].mean()

City
Austin           81216.000000
Chicago          76869.363636
New York         70484.133333
San Francisco    87144.727273
Name: Salary, dtype: float64

In [217]:
### dataframe concat merge

In [218]:
df1 = pd.read_csv("7-concat_data1.csv")

df2 = pd.read_csv("7-concat_data2.csv")

In [219]:
df1

   Employee_ID    Name Department
0            1   Emp_1    Finance
1            2   Emp_2  Marketing
2            3   Emp_3         HR
3            4   Emp_4    Finance
4            5   Emp_5    Finance
5            6   Emp_6  Marketing
6            7   Emp_7         HR
7            8   Emp_8         HR
8            9   Emp_9    Finance
9           10  Emp_10         IT

In [220]:
df2

   Employee_ID    Name Department
0           11  Emp_11    Finance
1           12  Emp_12    Finance
2           13  Emp_13    Finance
3           14  Emp_14    Finance
4           15  Emp_15  Marketing
5           16  Emp_16         HR
6           17  Emp_17  Marketing
7           18  Emp_18  Marketing
8           19  Emp_19  Marketing
9           20  Emp_20    Finance

In [224]:
df_concat = pd.concat([df1, df2], ignore_index= True) # ya df ya da series olmalı, ignore index ise indexleri göz ardı et demek.

In [222]:
df_concat

    Employee_ID    Name Department
0             1   Emp_1    Finance
1             2   Emp_2  Marketing
2             3   Emp_3         HR
3             4   Emp_4    Finance
4             5   Emp_5    Finance
5             6   Emp_6  Marketing
6             7   Emp_7         HR
7             8   Emp_8         HR
8             9   Emp_9    Finance
9            10  Emp_10         IT
10           11  Emp_11    Finance
11           12  Emp_12    Finance
12           13  Emp_13    Finance
13           14  Emp_14    Finance
14           15  Emp_15  Marketing
15           16  Emp_16         HR
16           17  Emp_17  Marketing
17           18  Emp_18  Marketing
18           19  Emp_19  Marketing
19           20  Emp_20    Finance

##### merge
-- İki df'i ortak bir anahtar sütun üzerinden birleştirmeye yarıyor. SQL'deki join mantığı aslında. <p>
-- En temel join türü INNER'dır. Her iki tabloda eşleşen kayıtları getirir. <p>

In [226]:
df_merge1 = pd.read_csv("7-merge_data1.csv")
df_merge2 = pd.read_csv("7-merge_data2.csv")

In [227]:
df_merge1

   Employee_ID    Name Department
0            1   Emp_1         IT
1            2   Emp_2         HR
2            3   Emp_3         IT
3            4   Emp_4  Marketing
4            5   Emp_5  Marketing
5            6   Emp_6         IT
6            7   Emp_7         IT
7            8   Emp_8         IT
8            9   Emp_9  Marketing
9           10  Emp_10  Marketing

In [228]:
df_merge2

   Employee_ID  Salary  Experience
0            5   55658           3
1            1  114478           5
2           12   48431          19
3           10   32747           7
4            6   89150           9
5           13   95725           7
6            9   65773           4
7           11   86886          18

In [ ]:
df_merge1.merge(df_merge2, on= "Employee_ID", how="inner") #eşleşenler birleşir.

   Employee_ID    Name Department  Salary  Experience
0            1   Emp_1         IT  114478           5
1            5   Emp_5  Marketing   55658           3
2            6   Emp_6         IT   89150           9
3            9   Emp_9  Marketing   65773           4
4           10  Emp_10  Marketing   32747           7

In [235]:
df_merge1.merge(df_merge2, on = "Employee_ID", how = "outer") # eşleşen birleşir, eşleşmeyen nan gelir.

    Employee_ID    Name Department    Salary  Experience
0             1   Emp_1         IT  114478.0         5.0
1             2   Emp_2         HR       NaN         NaN
2             3   Emp_3         IT       NaN         NaN
3             4   Emp_4  Marketing       NaN         NaN
4             5   Emp_5  Marketing   55658.0         3.0
5             6   Emp_6         IT   89150.0         9.0
6             7   Emp_7         IT       NaN         NaN
7             8   Emp_8         IT       NaN         NaN
8             9   Emp_9  Marketing   65773.0         4.0
9            10  Emp_10  Marketing   32747.0         7.0
10           11     NaN        NaN   86886.0        18.0
11           12     NaN        NaN   48431.0        19.0
12           13     NaN        NaN   95725.0         7.0

In [239]:
df_merge1.merge(df_merge2, on = "Employee_ID", how= "left") #sol tabloyu alır, sağdakiyle eşleştirir (eşleşenleri)

   Employee_ID    Name Department    Salary  Experience
0            1   Emp_1         IT  114478.0         5.0
1            2   Emp_2         HR       NaN         NaN
2            3   Emp_3         IT       NaN         NaN
3            4   Emp_4  Marketing       NaN         NaN
4            5   Emp_5  Marketing   55658.0         3.0
5            6   Emp_6         IT   89150.0         9.0
6            7   Emp_7         IT       NaN         NaN
7            8   Emp_8         IT       NaN         NaN
8            9   Emp_9  Marketing   65773.0         4.0
9           10  Emp_10  Marketing   32747.0         7.0

In [240]:
df_merge1.merge(df_merge2, on = "Employee_ID", how= "right") #sağ tabloyu alır, soldakiyle eşleştirir (eşleşenleri)

   Employee_ID    Name Department  Salary  Experience
0            5   Emp_5  Marketing   55658           3
1            1   Emp_1         IT  114478           5
2           12     NaN        NaN   48431          19
3           10  Emp_10  Marketing   32747           7
4            6   Emp_6         IT   89150           9
5           13     NaN        NaN   95725           7
6            9   Emp_9  Marketing   65773           4
7           11     NaN        NaN   86886          18

#### apply

--Apply mantık olarak, benim verdiğim fonksiyonu dataframe içindeki parçalara uygula anlamına gelir. <p>

--Pandas içerisindeki mevcut fonksiyonlar da kullanılabilirken, kendimizin tanımladığı fonksiyonlar da df içine uygulanabilir. <p>

-- Daha çok bir kural seti üzerindne yeni bir kolon oluşturmak için kullanılır.

In [242]:
df = pd.read_csv("8-apply_function_data.csv")

In [243]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [244]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [245]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [246]:
df.describe()

       Employee_ID         Salary  Experience  Performance_Score
count   100.000000     100.000000  100.000000          100.00000
mean     50.500000   77508.090000   12.090000            3.03000
std      29.011492   26083.327596    7.543939            1.41746
min       1.000000   30206.000000    1.000000            1.00000
25%      25.750000   54347.500000    5.000000            2.00000
50%      50.500000   80932.000000   12.000000            3.00000
75%      75.250000   97620.500000   19.000000            4.00000
max     100.000000  119474.000000   24.000000            5.00000

In [248]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [250]:
"""
Case1
-----
Dataframe, salarye göre yüksek, orta ve düşük maaş kategorisi ekle. Fonksiyon yaz,
daha sonrasında bu fonkisyonu apply ile dataframe ekle.
"""

'\nCase1\n-----\nDataframe, salarye göre yüksek, orta ve düşük maaş kategorisi ekle. Fonksiyon yaz,\ndaha sonrasında bu fonkisyonu apply ile dataframe ekle.\n'

In [251]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [252]:
def salary_category (salary):
    if salary < 50000:
        return "Low"
    elif 50000 <= salary < 80000:
        return "Medium"
    else:
        return "High"

In [255]:
df["Salary_Category"] = df["Salary"].apply(salary_category)

In [256]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,High
1,2,Emp_2,Sales,52662,24,3,Medium
2,3,Emp_3,Finance,38392,5,3,Low
3,4,Emp_4,Sales,60535,20,3,Medium
4,5,Emp_5,Sales,108603,2,2,High
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High
96,97,Emp_97,Sales,100467,22,2,High
97,98,Emp_98,IT,82662,23,3,High
98,99,Emp_99,IT,42688,22,1,Low
99,100,Emp_100,HR,55342,14,3,Medium

In [278]:
"""
Case2
-----
Experience > 10 --> performance_score + 1

İki yolu var:
1) Experience kolonu ile bir fonksiyon yazıp 10'dan fazla ise 1 değilse 0 döndür.
Daha sonrasında bu oluşturduğumuz 1-0'lı kolonu performance scorea ile toplatıp yeni bir 
kolon oluştur.
2) fonksiyon içerisinde row yazarak direkt olarak tüm rowları olaya dahil edip koşul
kontrolü yapmak

"""

"\nCase2\n-----\nExperience > 10 --> performance_score + 1\n\nİki yolu var:\n1) Experience kolonu ile bir fonksiyon yazıp 10'dan fazla ise 1 değilse 0 döndür.\nDaha sonrasında bu oluşturduğumuz 1-0'lı kolonu performance scorea ile toplatıp yeni bir \nkolon oluştur.\n2) fonksiyon içerisinde row yazarak direkt olarak tüm rowları olaya dahil edip koşul\nkontrolü yapmak\n\n"

In [272]:
def ps_buff(experience):
    if experience > 10:
        return 1
    else:
        return 0

In [274]:
df["Adjusted"] = df["Experience"].apply(ps_buff)

In [275]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted
0,1,Emp_1,Marketing,82251,6,5,High,0
1,2,Emp_2,Sales,52662,24,3,Medium,1
2,3,Emp_3,Finance,38392,5,3,Low,0
3,4,Emp_4,Sales,60535,20,3,Medium,1
4,5,Emp_5,Sales,108603,2,2,High,0
...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1
96,97,Emp_97,Sales,100467,22,2,High,1
97,98,Emp_98,IT,82662,23,3,High,1
98,99,Emp_99,IT,42688,22,1,Low,1
99,100,Emp_100,HR,55342,14,3,Medium,1

In [276]:
df["New Score"] = df["Performance_Score"] + df["Adjusted"]

In [277]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,New Score
0,1,Emp_1,Marketing,82251,6,5,High,0,5
1,2,Emp_2,Sales,52662,24,3,Medium,1,4
2,3,Emp_3,Finance,38392,5,3,Low,0,3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4
4,5,Emp_5,Sales,108603,2,2,High,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5
96,97,Emp_97,Sales,100467,22,2,High,1,3
97,98,Emp_98,IT,82662,23,3,High,1,4
98,99,Emp_99,IT,42688,22,1,Low,1,2
99,100,Emp_100,HR,55342,14,3,Medium,1,4

In [282]:
def adjusted_func(row):
    if row["Experience"] > 10:
        return row["Performance_Score"] + 1
    else:
        return row["Performance_Score"]

In [283]:
df["Adjusted_V2"] = df.apply(adjusted_func, axis=1)

In [285]:
df["Formated_Name"] = df["Name"].apply(lambda x : x.replace("_", " "))

In [286]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,New Score,Adjusted_V2,Formated_Name
0,1,Emp_1,Marketing,82251,6,5,High,0,5,5,Emp 1
1,2,Emp_2,Sales,52662,24,3,Medium,1,4,4,Emp 2
2,3,Emp_3,Finance,38392,5,3,Low,0,3,3,Emp 3
3,4,Emp_4,Sales,60535,20,3,Medium,1,4,4,Emp 4
4,5,Emp_5,Sales,108603,2,2,High,0,2,2,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,High,1,5,5,Emp 96
96,97,Emp_97,Sales,100467,22,2,High,1,3,3,Emp 97
97,98,Emp_98,IT,82662,23,3,High,1,4,4,Emp 98
98,99,Emp_99,IT,42688,22,1,Low,1,2,2,Emp 99
99,100,Emp_100,HR,55342,14,3,Medium,1,4,4,Emp 100

### PANDAS ALIŞTIRMALARI

In [308]:
## Dataframe oluşturma

## 100 tane order_id (1'den 100'e)

sehir_listesi = ["İstanbul", "İzmir", "Ankara"]

order_id = list(range(1,101))

age = np.random.randint(18,60, size = 100)

city = np.random.choice(sehir_listesi, size = 100)

In [309]:
df = pd.DataFrame({
    "order_id": order_id,
    "age": age,
    "city": city
})

In [310]:
df

    order_id  age      city
0          1   51  İstanbul
1          2   54  İstanbul
2          3   46    Ankara
3          4   57  İstanbul
4          5   44     İzmir
..       ...  ...       ...
95        96   58     İzmir
96        97   42  İstanbul
97        98   36  İstanbul
98        99   34  İstanbul
99       100   46    Ankara

[100 rows x 3 columns]

In [311]:
df.head()

   order_id  age      city
0         1   51  İstanbul
1         2   54  İstanbul
2         3   46    Ankara
3         4   57  İstanbul
4         5   44     İzmir

In [312]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  100 non-null    int64
 1   age       100 non-null    int64
 2   city      100 non-null    object
dtypes: int64(2), object(1)
memory usage: 2.5+ KB

In [313]:
df.describe()

         order_id         age
count  100.000000  100.000000
mean    50.500000   40.250000
std     29.011492   12.550001
min      1.000000   18.000000
25%     25.750000   29.750000
50%     50.500000   41.500000
75%     75.250000   53.000000
max    100.000000   58.000000

In [317]:
## Yaşı 30'dan büyük olanları getir:

df[df["age"] > 30 ]

    order_id  age      city
0          1   51  İstanbul
1          2   54  İstanbul
2          3   46    Ankara
3          4   57  İstanbul
4          5   44     İzmir
..       ...  ...       ...
95        96   58     İzmir
96        97   42  İstanbul
97        98   36  İstanbul
98        99   34  İstanbul
99       100   46    Ankara

[73 rows x 3 columns]

In [319]:
## Sadece İstanbul'da yaşayanları getir:

df[df["city"] == "İstanbul"]

    order_id  age      city
0          1   51  İstanbul
1          2   54  İstanbul
3          4   57  İstanbul
8          9   46  İstanbul
10        11   51  İstanbul
12        13   57  İstanbul
13        14   39  İstanbul
14        15   29  İstanbul
15        16   32  İstanbul
18        19   31  İstanbul
21        22   23  İstanbul
22        23   20  İstanbul
23        24   22  İstanbul
33        34   58  İstanbul
39        40   22  İstanbul
47        48   32  İstanbul
48        49   20  İstanbul
51        52   36  İstanbul
70        71   27  İstanbul
73        74   35  İstanbul
74        75   51  İstanbul
80        81   26  İstanbul
81        82   22  İstanbul
88        89   45  İstanbul
90        91   48  İstanbul
92        93   49  İstanbul
96        97   42  İstanbul
97        98   36  İstanbul
98        99   34  İstanbul

In [320]:
## Yukarıdaki ikisinin birleştirilmesi hem & hem merge ile.

In [324]:
df[(df["age"] > 30) & (df["city"] == "İstanbul")]

    order_id  age      city
0          1   51  İstanbul
1          2   54  İstanbul
3          4   57  İstanbul
8          9   46  İstanbul
10        11   51  İstanbul
12        13   57  İstanbul
13        14   39  İstanbul
15        16   32  İstanbul
18        19   31  İstanbul
33        34   58  İstanbul
47        48   32  İstanbul
51        52   36  İstanbul
73        74   35  İstanbul
74        75   51  İstanbul
88        89   45  İstanbul
90        91   48  İstanbul
92        93   49  İstanbul
96        97   42  İstanbul
97        98   36  İstanbul
98        99   34  İstanbul

In [325]:
## Hangi şehirde ortalama yaş daha yüksek?

grouped_city = df.groupby("city")

In [330]:
grouped_city.mean("age")

           order_id        age
city
Ankara    53.000000  39.181818
İstanbul  46.413793  37.758621
İzmir     51.447368  43.078947

In [331]:
grouped_city["age"].count()

city
Ankara      33
İstanbul    29
İzmir       38
Name: age, dtype: int64

In [332]:
df.groupby("city")["age"].std()

city
Ankara      12.800036
İstanbul    12.500443
İzmir       12.139686
Name: age, dtype: float64

In [333]:
df.groupby("city")["age"].agg(["min", "max"])

          min  max
city
Ankara     18   58
İstanbul   20   58
İzmir      20   58

In [336]:
""" 
Yorumlar:

--En yüksek yaş ortalaması İzmir'de olmasına rağmen, bu tip yorumlarda
ortalama kullanılmamalı. Çünkü outlier değerler (aykırı değerler) olabilir. 
Yani yaşı 90 olan 2 kişi, yaşı 20 olan 5 kişilik bir grubun ortalamasını yukarı çeker.

--Bu tip analizlerde en mantıklı tespit median ile yapılır. Median ile, verisetinin
tam ortasındaki değerler baz alınır. Böylelikle outlier değerlerden kaçınılır.

Mean > Median → sağa çarpık dağılım

Mean < Median → sola çarpık dağılım

"""

" \nYorumlar:\n\n--En yüksek yaş ortalaması İzmir'de olmasına rağmen, bu tip yorumlarda\nortalama kullanılmamalı. Çünkü outlier değerler (aykırı değerler) olabilir. \nYani yaşı 90 olan 2 kişi, yaşı 20 olan 5 kişilik bir grubun ortalamasını yukarı çeker.\n\n--Bu tip analizlerde en mantıklı tespit median ile yapılır. Median ile, verisetinin\ntam ortasındaki değerler baz alınır. Böylelikle outlier değerlerden kaçınılır.\n\nMean > Median → sağa çarpık dağılım\n\nMean < Median → sola çarpık dağılım\n\n"

In [335]:
df.groupby("city")["age"].agg(["mean", "median", "std"])

               mean  median        std
city
Ankara    39.181818    41.0  12.800036
İstanbul  37.758621    36.0  12.500443
İzmir     43.078947    46.0  12.139686

In [345]:
amount = np.random.randint(100,1000, size = 100)

In [350]:
df["amount"] = amount

In [353]:
df.drop(columns=["Amount"])

    order_id  age      city  amount
0          1   51  İstanbul     541
1          2   54  İstanbul     315
2          3   46    Ankara     139
3          4   57  İstanbul     148
4          5   44     İzmir     626
..       ...  ...       ...     ...
95        96   58     İzmir     619
96        97   42  İstanbul     293
97        98   36  İstanbul     898
98        99   34  İstanbul     882
99       100   46    Ankara     660

[100 rows x 4 columns]

In [357]:
amount_filter = df[df["amount"] > 500]

In [364]:
amount_filter[["order_id", "city", "amount"]].describe()

         order_id      amount
count   54.000000   54.000000
mean    49.981481  747.703704
std     30.496824  136.871601
min      1.000000  532.000000
25%     22.250000  625.250000
50%     50.000000  752.000000
75%     75.750000  878.500000
max    100.000000  985.000000

In [368]:
amount_filter["order_id"].count()

np.int64(54)

In [369]:
amount_filter["amount"].mean()

np.float64(747.7037037037037)

In [370]:
"""
Case 2 — Şehir Bazlı Satış Analizi

Senaryo

Her şehir için şunları bul:

Toplam sipariş sayısı

Ortalama sipariş tutarı

Toplam kazanç (sum)

"""

'\nCase 2 — Şehir Bazlı Satış Analizi\n\nSenaryo\n\nHer şehir için şunları bul:\n\nToplam sipariş sayısı\n\nOrtalama sipariş tutarı\n\nToplam kazanç (sum)\n\n'

In [376]:
df_nihai = df.groupby("city")["amount"].agg(
    siparis_sayisi = "count", 
    ortalama_tutar = "mean", 
    toplam_kazanc = "sum")

In [377]:
df_nihai["siparis_basi_kazanc"] = df_nihai["siparis_sayisi"] / df_nihai["toplam_kazanc"]

In [378]:
df_nihai

          siparis_sayisi  ortalama_tutar  toplam_kazanc  siparis_basi_kazanc
city
Ankara                33      571.303030          18853             0.001750
İstanbul              29      554.275862          16074             0.001804
İzmir                 38      516.631579          19632             0.001936